spring:
  application:
    name: result
    version: 1.0.0
    author:
      name: Pedro Carara
      email: cararax@gmail.com
server:
  port: 8083

rabbitmq:
  host: localhost
  port: '15672'
  username: guest
  password: guest

  vote:
    exchange: vote.exchange
    queue: vote.queue
    routingkey: vote.routingkey

  result:
    exchange: result.exchange
    queue: result.queue
    routingkey: result.routingkey

